{
  "GATK_best_practices_RNA.fastqR1": "File",
  "GATK_best_practices_RNA.fastqR2": "File? (optional)",
  "GATK_best_practices_RNA.dbsnp": "File",
  "GATK_best_practices_RNA.dbsnpIdx": "File",
  "GATK_best_practices_RNA.knownSites": "Array[File]",
  "GATK_best_practices_RNA.knownSitesIdx": "Array[File]",
  "GATK_best_practices_RNA.genomeDir": "File",
  "GATK_best_practices_RNA.outputPath": "String",
  "GATK_best_practices_RNA.refDict": "File",
  "GATK_best_practices_RNA.refFai": "File",
  "GATK_best_practices_RNA.refFasta": "File",

  "GATK_best_practices_RNA.scatterCount": 4,
  "GATK_best_practices_RNA.regionOfInterest": "File? (optional)",
  "GATK_best_practices_RNA.subString": "(_S[0-9]+)?(_L[0-9]+)?([_.]?R[12])?(_[0-9]+)?.(fastq|fq)(.gz)?",
  "GATK_best_practices_RNA.subStringReplace": "",
  "GATK_best_practices_RNA.name": "String? (optional)",

  "GATK_best_practices_RNA.ALIGNREADS.alignEndsProtrudeConc": true,
  "GATK_best_practices_RNA.ALIGNREADS.alignEndsProtrudeMax": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignEndsTypeE2E": false,
  "GATK_best_practices_RNA.ALIGNREADS.alignInsertionFlushRight": false,
  "GATK_best_practices_RNA.ALIGNREADS.alignIntronMax": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignIntronMin": 21,
  "GATK_best_practices_RNA.ALIGNREADS.alignMatesGapMax": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJDBoverhangMin": 3,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJoverhangMin": 5,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJstitchMismatchNmax1": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJstitchMismatchNmax2": -1,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJstitchMismatchNmax3": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignSJstitchMismatchNmax4": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignSoftClipAtReferenceEnds": true,
  "GATK_best_practices_RNA.ALIGNREADS.alignSplicedMateMapLmin": 0,
  "GATK_best_practices_RNA.ALIGNREADS.alignSplicedMateMapLminOverLmate": 0.66,
  "GATK_best_practices_RNA.ALIGNREADS.alignTranscriptsPerReadNmax": 10000,
  "GATK_best_practices_RNA.ALIGNREADS.alignTranscriptsPerWindowNmax": 100,
  "GATK_best_practices_RNA.ALIGNREADS.alignWindowsPerReadNmax": 10000,
  "GATK_best_practices_RNA.ALIGNREADS.bamRemoveDuplicatesMate2basesN": 0,
  "GATK_best_practices_RNA.ALIGNREADS.clip3pAdapterMMp": [0.1],
  "GATK_best_practices_RNA.ALIGNREADS.clip3pAdapterSeq": ["-"],
  "GATK_best_practices_RNA.ALIGNREADS.clip3pAfterAdapterNbases": [0],
  "GATK_best_practices_RNA.ALIGNREADS.clip3pNbases": [0],
  "GATK_best_practices_RNA.ALIGNREADS.clip5pNbases": [0],
  "GATK_best_practices_RNA.ALIGNREADS.clipAdapterHamming": true,
  "GATK_best_practices_RNA.ALIGNREADS.genomeLoad": false,
  "GATK_best_practices_RNA.ALIGNREADS.limitBAMsortRAM": 0,
  "GATK_best_practices_RNA.ALIGNREADS.limitIObufferSize": 150000000,
  "GATK_best_practices_RNA.ALIGNREADS.limitNreadsSoft": -1,
  "GATK_best_practices_RNA.ALIGNREADS.limitOutSAMoneReadBytes": 100000,
  "GATK_best_practices_RNA.ALIGNREADS.limitOutSJcollapsed": 1000000,
  "GATK_best_practices_RNA.ALIGNREADS.limitOutSJoneRead": 1000,
  "GATK_best_practices_RNA.ALIGNREADS.limitSjdbInsertNsj": 1000000,
  "GATK_best_practices_RNA.ALIGNREADS.markDup": true,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterBySJ": true,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMatchNmin": 0,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMatchNminOverLread": 0.66,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMismatchNmax": 10,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMismatchNoverLmax": 0.3,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMismatchNoverReadLmax": 0.04,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMultimapNmax": 20,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterMultimapScoreRange": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterNonCanonical": false,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterScoreMin": 0,
  "GATK_best_practices_RNA.ALIGNREADS.outFilterScoreMinOverLread": 0.66,
  "GATK_best_practices_RNA.ALIGNREADS.outReadsUnmapped": false,
  "GATK_best_practices_RNA.ALIGNREADS.outSAMattributes": ["NH", "HI", "AS", "nM"],
  "GATK_best_practices_RNA.ALIGNREADS.outSAMmapqUnique": 60,
  "GATK_best_practices_RNA.ALIGNREADS.outSAMmodeQuality": true,
  "GATK_best_practices_RNA.ALIGNREADS.outSAMstrandFieldIntron": true,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountTotalMin1": 3,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountTotalMin2": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountTotalMin3": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountTotalMin4": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountUniqueMin1": 3,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountUniqueMin2": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountUniqueMin3": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterCountUniqueMin4": 1,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterDistToOtherSJmin1": 10,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterDistToOtherSJmin2": 0,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterDistToOtherSJmin3": 5,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterDistToOtherSJmin4": 10,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterIntronMaxVsReadN": [50000, 100000, 200000],
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterOverhangMin1": 30,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterOverhangMin2": 12,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterOverhangMin3": 12,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterOverhangMin4": 12,
  "GATK_best_practices_RNA.ALIGNREADS.outSJfilterReadsUniq": false,
  "GATK_best_practices_RNA.ALIGNREADS.path_exe": "STAR",
  "GATK_best_practices_RNA.ALIGNREADS.peOverlapMMp": 0.01,
  "GATK_best_practices_RNA.ALIGNREADS.peOverlapNbasesMin": 0,
  "GATK_best_practices_RNA.ALIGNREADS.platformReads": "ILLUMINA",
  "GATK_best_practices_RNA.ALIGNREADS.quantModeSAM": true,
  "GATK_best_practices_RNA.ALIGNREADS.quantTranscriptomeBAMcompression": -1,
  "GATK_best_practices_RNA.ALIGNREADS.quantTranscriptomeBanSingleend": false,
  "GATK_best_practices_RNA.ALIGNREADS.readFilesCommand": "zcat",
  "GATK_best_practices_RNA.ALIGNREADS.readQualityScoreBase": 33,
  "GATK_best_practices_RNA.ALIGNREADS.removeInconsistentStrands": true,
  "GATK_best_practices_RNA.ALIGNREADS.scoreDelBase": -2,
  "GATK_best_practices_RNA.ALIGNREADS.scoreDelOpen": -2,
  "GATK_best_practices_RNA.ALIGNREADS.scoreGap": 0,
  "GATK_best_practices_RNA.ALIGNREADS.scoreGapATAC": -8,
  "GATK_best_practices_RNA.ALIGNREADS.scoreGapGCAG": -4,
  "GATK_best_practices_RNA.ALIGNREADS.scoreGapNoncan": -8,
  "GATK_best_practices_RNA.ALIGNREADS.scoreGenomicLengthLog2scale": -0.25,
  "GATK_best_practices_RNA.ALIGNREADS.scoreInsBase": -2,
  "GATK_best_practices_RNA.ALIGNREADS.scoreInsOpen": -2,
  "GATK_best_practices_RNA.ALIGNREADS.scoreStitchSJshift": 1,
  "GATK_best_practices_RNA.ALIGNREADS.seedMapMin": 5,
  "GATK_best_practices_RNA.ALIGNREADS.seedMultimapNmax": 10000,
  "GATK_best_practices_RNA.ALIGNREADS.seedNoneLociPerWindow": 10,
  "GATK_best_practices_RNA.ALIGNREADS.seedPerReadNmax": 1000,
  "GATK_best_practices_RNA.ALIGNREADS.seedPerWindowNmax": 50,
  "GATK_best_practices_RNA.ALIGNREADS.seedSearchLmax": 0,
  "GATK_best_practices_RNA.ALIGNREADS.seedSearchStartLmax": 50,
  "GATK_best_practices_RNA.ALIGNREADS.seedSearchStartLmaxOverLread": 1.0,
  "GATK_best_practices_RNA.ALIGNREADS.seedSplitMin": 12,
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFfeatureExon": "exon",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFtagExonParentGene": "gene_id",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFtagExonParentGeneName": ["gene_name"],
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFtagExonParentGeneType": ["gene_type", "gene_biotype"],
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFtagExonParentTranscript": "transcript_id",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbInsertSaveAll": false,
  "GATK_best_practices_RNA.ALIGNREADS.sjdbOverhang": 100,
  "GATK_best_practices_RNA.ALIGNREADS.sjdbScore": 2,
  "GATK_best_practices_RNA.ALIGNREADS.sorted": true,
  "GATK_best_practices_RNA.ALIGNREADS.subString": "(_S[0-9]+)?(_L[0-9][0-9][0-9])?(_R[12])?(_[0-9][0-9][0-9])?.(fastq|fq)(.gz)?",
  "GATK_best_practices_RNA.ALIGNREADS.subStringReplace": "",
  "GATK_best_practices_RNA.ALIGNREADS.twopass1readsN": -1,
  "GATK_best_practices_RNA.ALIGNREADS.twopassMode": true,
  "GATK_best_practices_RNA.ALIGNREADS.waspOutputMode": false,
  "GATK_best_practices_RNA.ALIGNREADS.winAnchorDistNbins": 9,
  "GATK_best_practices_RNA.ALIGNREADS.winAnchorMultimapNmax": 50,
  "GATK_best_practices_RNA.ALIGNREADS.winBinNbits": 16,
  "GATK_best_practices_RNA.ALIGNREADS.winFlankNbins": 4,
  "GATK_best_practices_RNA.ALIGNREADS.memory": "32G",
  "GATK_best_practices_RNA.ALIGNREADS.memoryByThreads": 768,
  "GATK_best_practices_RNA.ALIGNREADS.threads": 1,
  "GATK_best_practices_RNA.APPLYBQSR.bamIndex": true,
  "GATK_best_practices_RNA.APPLYBQSR.bamMD5": true,
  "GATK_best_practices_RNA.APPLYBQSR.globalQScorePrior": -1,
  "GATK_best_practices_RNA.APPLYBQSR.intersectionRule": false,
  "GATK_best_practices_RNA.APPLYBQSR.intervalsPadding": 0,
  "GATK_best_practices_RNA.APPLYBQSR.memoryByThreads": 768,
  "GATK_best_practices_RNA.APPLYBQSR.originalQScore": false,
  "GATK_best_practices_RNA.APPLYBQSR.overlappingRule": false,
  "GATK_best_practices_RNA.APPLYBQSR.path_exe": "gatk",
  "GATK_best_practices_RNA.APPLYBQSR.preserveQScoreLT": 6,
  "GATK_best_practices_RNA.APPLYBQSR.quantizeQual": 0,
  "GATK_best_practices_RNA.APPLYBQSR.subStringReplace_intervals": "$1",
  "GATK_best_practices_RNA.APPLYBQSR.subString_intervals": "([0-9]+)-scattered.interval_list",
  "GATK_best_practices_RNA.APPLYBQSR.suffix": ".bqsr",
  "GATK_best_practices_RNA.APPLYBQSR.threads": 1,
  "GATK_best_practices_RNA.BASERECALIBRATOR.ext": ".recal",
  "GATK_best_practices_RNA.BASERECALIBRATOR.gapPenality": 40,
  "GATK_best_practices_RNA.BASERECALIBRATOR.indelDefaultQual": 45,
  "GATK_best_practices_RNA.BASERECALIBRATOR.indelKmer": 3,
  "GATK_best_practices_RNA.BASERECALIBRATOR.intersectionRule": false,
  "GATK_best_practices_RNA.BASERECALIBRATOR.intervalsPadding": 0,
  "GATK_best_practices_RNA.BASERECALIBRATOR.lowQualTail": 2,
  "GATK_best_practices_RNA.BASERECALIBRATOR.maxCycle": 500,
  "GATK_best_practices_RNA.BASERECALIBRATOR.memoryByThreads": 768,
  "GATK_best_practices_RNA.BASERECALIBRATOR.mismatchKmer": 2,
  "GATK_best_practices_RNA.BASERECALIBRATOR.overlappingRule": false,
  "GATK_best_practices_RNA.BASERECALIBRATOR.path_exe": "gatk",
  "GATK_best_practices_RNA.BASERECALIBRATOR.subStringReplace_intervals": "$1",
  "GATK_best_practices_RNA.BASERECALIBRATOR.subString_intervals": "([0-9]+)-scattered.interval_list",
  "GATK_best_practices_RNA.BASERECALIBRATOR.threads": 1,
  "GATK_best_practices_RNA.BED2INTERVALS.ext": ".intervals",
  "GATK_best_practices_RNA.BED2INTERVALS.memoryByThreads": 768,
  "GATK_best_practices_RNA.BED2INTERVALS.threads": 1,
  "GATK_best_practices_RNA.FAI2BED.memoryByThreads": 768,
  "GATK_best_practices_RNA.FAI2BED.subString": ".?(fa)?(sta)?.fai$",
  "GATK_best_practices_RNA.FAI2BED.subStringReplace": ".bed",
  "GATK_best_practices_RNA.FAI2BED.threads": 1,
  "GATK_best_practices_RNA.GATHERBAMFILES.bamMD5": true,
  "GATK_best_practices_RNA.GATHERBAMFILES.compressionLevel": 6,
  "GATK_best_practices_RNA.GATHERBAMFILES.maxRecordsInRam": 500000,
  "GATK_best_practices_RNA.GATHERBAMFILES.memoryByThreads": 768,
  "GATK_best_practices_RNA.GATHERBAMFILES.path_exe": "gatk",
  "GATK_best_practices_RNA.GATHERBAMFILES.subString": "(.[0-9]+)?.(sam|bam|cram)$",
  "GATK_best_practices_RNA.GATHERBAMFILES.subStringReplace": "",
  "GATK_best_practices_RNA.GATHERBAMFILES.suffix": ".gather",
  "GATK_best_practices_RNA.GATHERBAMFILES.threads": 1,
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.ext": ".bqsr.report",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.memoryByThreads": 768,
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.path_exe": "gatk",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.subString": "(.[0-9]+)?.recal$",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.subStringReplace": "",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.threads": 1,
  "GATK_best_practices_RNA.GATHERVCFFILES.memoryByThreads": 768,
  "GATK_best_practices_RNA.GATHERVCFFILES.path_exe": "gatk",
  "GATK_best_practices_RNA.GATHERVCFFILES.reorder": true,
  "GATK_best_practices_RNA.GATHERVCFFILES.subString": "(.[0-9]+)?.(vcf)$",
  "GATK_best_practices_RNA.GATHERVCFFILES.subStringReplace": ".gather",
  "GATK_best_practices_RNA.GATHERVCFFILES.threads": 1,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.annotateNumAlleleDiscovered": false,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.createVCFIdx": true,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.createVCFMD5": true,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.emitRefConfidence": "NONE",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.intersectionRule": false,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.intervalsPadding": 0,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.memoryByThreads": 768,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.overlappingRule": false,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.path_exe": "gatk",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.ploidy": 2,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.smithAndWaterman": "FASTEST_AVAILABLE",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.standCallConf": 30.0,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.subString": ".(sam|bam|cram)$",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.subStringIntervals": "([0-9]+)-scattered.interval_list$",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.subStringReplace": ".haplotypeCaller.vcf",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.subStringReplaceIntervals": ".$1",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.threads": 1,
  "GATK_best_practices_RNA.HAPLOTYPECALLER.useSoftClipped": false,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.bamIndex": true,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.bamMD5": true,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.intersectionRule": false,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.intervalsPadding": 0,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.memoryByThreads": 768,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.overlappingRule": false,
  "GATK_best_practices_RNA.LEFTALIGNINDELS.path_exe": "gatk",
  "GATK_best_practices_RNA.LEFTALIGNINDELS.suffix": ".leftAlign",
  "GATK_best_practices_RNA.LEFTALIGNINDELS.threads": 1,
  "GATK_best_practices_RNA.MARKDUP.compressionLevel": 6,
  "GATK_best_practices_RNA.MARKDUP.memoryByThreads": 768,
  "GATK_best_practices_RNA.MARKDUP.path_exe": "sambamba",
  "GATK_best_practices_RNA.MARKDUP.removeDuplicates": false,
  "GATK_best_practices_RNA.MARKDUP.suffix": ".markdup",
  "GATK_best_practices_RNA.MARKDUP.threads": 1,
  "GATK_best_practices_RNA.SORT.compressionLevel": 6,
  "GATK_best_practices_RNA.SORT.memoryByThreads": 768,
  "GATK_best_practices_RNA.SORT.path_exe": "sambamba",
  "GATK_best_practices_RNA.SORT.suffix": ".sort",
  "GATK_best_practices_RNA.SORT.threads": 1,
  "GATK_best_practices_RNA.SORT.uncompressedChuncks": false,
  "GATK_best_practices_RNA.SPLITINTERVALS.intersectionRule": false,
  "GATK_best_practices_RNA.SPLITINTERVALS.intervalsPadding": 0,
  "GATK_best_practices_RNA.SPLITINTERVALS.memoryByThreads": 768,
  "GATK_best_practices_RNA.SPLITINTERVALS.overlappingRule": false,
  "GATK_best_practices_RNA.SPLITINTERVALS.path_exe": "gatk",
  "GATK_best_practices_RNA.SPLITINTERVALS.subString": ".([a-zA-Z]*)$",
  "GATK_best_practices_RNA.SPLITINTERVALS.subStringReplace": "-split",
  "GATK_best_practices_RNA.SPLITINTERVALS.threads": 1,
  "GATK_best_practices_RNA.SPLITNCIGARREADS.memoryByThreads": 768,
  "GATK_best_practices_RNA.SPLITNCIGARREADS.path_exe": "gatk",
  "GATK_best_practices_RNA.SPLITNCIGARREADS.subString": "(.sam|.bam|.cram)$",
  "GATK_best_practices_RNA.SPLITNCIGARREADS.subStringReplace": ".spliNcigar.bam",
  "GATK_best_practices_RNA.SPLITNCIGARREADS.threads": 1,
  "GATK_best_practices_RNA.VARIANTFILTRATION.createVCFMD5": true,
  "GATK_best_practices_RNA.VARIANTFILTRATION.memoryByThreads": 768,
  "GATK_best_practices_RNA.VARIANTFILTRATION.path_exe": "gatk",
  "GATK_best_practices_RNA.VARIANTFILTRATION.subString": ".(vcf|bcf|vcf.gz)$",
  "GATK_best_practices_RNA.VARIANTFILTRATION.subStringReplace": ".filter.vcf",
  "GATK_best_practices_RNA.VARIANTFILTRATION.threads": 1,

  "GATK_best_practices_RNA.ALIGNREADS.genomeFastaFiles": "File? (optional)",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbBED": "File? (optional)",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTF": "File? (optional)",
  "GATK_best_practices_RNA.ALIGNREADS.sjdbGTFchrPrefix": "String? (optional)",
  "GATK_best_practices_RNA.APPLYBQSR.memory": "String? (optional)",
  "GATK_best_practices_RNA.APPLYBQSR.name": "String? (optional)",
  "GATK_best_practices_RNA.BASERECALIBRATOR.memory": "String? (optional)",
  "GATK_best_practices_RNA.BASERECALIBRATOR.name": "String? (optional)",
  "GATK_best_practices_RNA.BED2INTERVALS.memory": "String? (optional)",
  "GATK_best_practices_RNA.BED2INTERVALS.name": "String? (optional)",
  "GATK_best_practices_RNA.FAI2BED.memory": "String? (optional)",
  "GATK_best_practices_RNA.FAI2BED.name": "String? (optional)",
  "GATK_best_practices_RNA.GATHERBAMFILES.memory": "String? (optional)",
  "GATK_best_practices_RNA.GATHERBAMFILES.name": "String? (optional)",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.memory": "String? (optional)",
  "GATK_best_practices_RNA.GATHERBQSRREPORTS.name": "String? (optional)",
  "GATK_best_practices_RNA.GATHERVCFFILES.memory": "String? (optional)",
  "GATK_best_practices_RNA.GATHERVCFFILES.name": "String? (optional)",
  "GATK_best_practices_RNA.HAPLOTYPECALLER.memory": "String? (optional)",
  "GATK_best_practices_RNA.LEFTALIGNINDELS.memory": "String? (optional)",
  "GATK_best_practices_RNA.LEFTALIGNINDELS.name": "String? (optional)",
  "GATK_best_practices_RNA.MARKDUP.bufferSize": "Int? (optional)",
  "GATK_best_practices_RNA.MARKDUP.hashTableSize": "Int? (optional)",
  "GATK_best_practices_RNA.MARKDUP.memory": "String? (optional)",
  "GATK_best_practices_RNA.MARKDUP.overflowListSize": "Int? (optional)",
  "GATK_best_practices_RNA.MARKDUP.sample": "String? (optional)",
  "GATK_best_practices_RNA.MARKDUP.sortBufferSize": "Int? (optional)",
  "GATK_best_practices_RNA.MARKDUP.tempDir": "String? (optional)",
  "GATK_best_practices_RNA.SORT.filter": "String? (optional)",
  "GATK_best_practices_RNA.SORT.memory": "String? (optional)",
  "GATK_best_practices_RNA.SORT.sample": "String? (optional)",
  "GATK_best_practices_RNA.SORT.sortByReadName": "Boolean? (optional)",
  "GATK_best_practices_RNA.SORT.tempDir": "String? (optional)",
  "GATK_best_practices_RNA.SPLITINTERVALS.memory": "String? (optional)",
  "GATK_best_practices_RNA.SPLITINTERVALS.name": "String? (optional)",
  "GATK_best_practices_RNA.SPLITNCIGARREADS.memory": "String? (optional)",
  "GATK_best_practices_RNA.SPLITNCIGARREADS.name": "String? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.HomopolymerRegion": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.LowCoverage": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.LowMappingQuality": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.LowMappingQualityRankSum": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.LowReadPosRankSum": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.SORStrandBias": "Float? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.inIdx": "File? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.memory": "String? (optional)",
  "GATK_best_practices_RNA.VARIANTFILTRATION.name": "String? (optional)"
}
